name: healingbee
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_locales: ^3.0.0+1
  circle_flags: ^3.0.1
  url_launcher: ^6.0.13
  gradients: ^0.1.1+2
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  fluttertoast: ^8.2.2
  pinput: ^3.0.1
  modal_progress_hud_nsn: ^0.4.0
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  shared_preferences: ^2.2.1
  http: ^1.1.0
  mockito: ^5.4.2
  cloud_firestore: ^4.9.2
  provider: ^6.0.5
  loading_indicator: ^3.1.1
  bubble_bottom_bar: ^2.0.0
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  bottom_navy_bar: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  firebase_storage: ^11.2.8
  card_swiper: ^3.0.1
  carousel_slider: ^4.2.1
  audioplayers: ^5.2.0
  speech_to_text: ^6.3.0
  flutter_sound: ^9.2.13
  just_audio_cache: ^0.1.2
  just_audio: ^0.9.35
  fl_chart: ^0.64.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/spalsh_logo.png"



dev_dependencies:
  flutter_test:
    sdk: flutter








  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/upda.png
    - assets/images/pass.png
    - assets/images/mail.png
    - assets/images/profile.png
    - assets/images/logo1.png
    - assets/images/detail_head.png
    - assets/images/front_image.png
    - assets/images/spalsh_logo.png
    - assets/icons/assesment.png
    - assets/icons/home.png
    - assets/icons/profile.png
    - assets/icons/quick_note.png
    - assets/images/arrow.png
    - assets/images/thalapathy.png
    - assets/images/nature.jpg
    - assets/images/man-covering-face-with-hands.jpg
    - assets/images/human.jpg
    - assets/images/apple.png
    - assets/images/mobile.png
    - assets/images/fb.png
    - assets/images/google.png
    - assets/images/personalized_guidance.png
    - assets/images/track_progress.png
    - assets/images/supportive_community.png
    - assets/images/voice_notes.png
    - assets/locales/en.json
    - assets/locales/gu.json
    - assets/locales/hi.json
    - assets/locales/kn.json
    - assets/locales/ml.json
    - assets/locales/mr.json
    - assets/locales/pa.json
    - assets/locales/ta.json
    - assets/locales/te.json
    - assets/locales/ur.json
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Neue Plak
       fonts:
         - asset: fonts/Neue Plak Text Bold.ttf
  #         style: italic
     - family: Ubuntu
       fonts:
         - asset: fonts/Ubuntu-M.ttf
  #         weight: 700


     - family: lufga
       fonts:
         - asset: fonts/Fontspring-DEMO-lufga-medium.otf

     - family: ReadexPro
       fonts:
         - asset: fonts/ReadexPro-Regular.ttf

     - family: YukitaSans
       fonts:
         - asset: fonts/YukitaSans-Regular-BF640fc93d5bd03.otf

     - family: Fantasista
       fonts:
         - asset: fonts/Fantasista-JRjvK.ttf

     - family:  Poppins
       fonts:
         - asset: fonts/Poppins-Regular.ttf


     - family: Helvetica
       fonts:
         - asset: fonts/Helvetica.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
